Секция заявка, первая часть
OlenaPatlata/team pull request #10
Opened 2021-12-28 19:55 UTC by OlenaPatlata

Сделана половина работы по секции request

2021-12-28 21:23 UTC, Persatyi requested changes

2021-12-28 21:23 UTC, Persatyi commented on src/sass/layout/_request.scss
> +      margin-bottom: 40px;
Этим маржином ты пробиваеш родителя, он лишний. Этот маржин есть у родителя

2021-12-28 21:23 UTC, Persatyi commented on src/sass/layout/_request.scss
> +    margin-bottom: 15px;
Маржин задаем обертке

2021-12-28 21:23 UTC, Persatyi commented on src/sass/layout/_request.scss
> +      margin-bottom: 0;
это лишнее, разве что для обнуления

2021-12-28 21:23 UTC, Persatyi commented on src/sass/layout/_request.scss
> +  align-content: flex-start;
align-content: flex-start; это дефолтное значение, его можно не писать

2021-12-28 21:23 UTC, Persatyi commented on src/sass/layout/_request.scss
> +.title {
Это лишний код, для этого есть отдельный файл "_title"

2021-12-29 06:06 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +.title {
Я этот код у тебя и скопировала, чтобы видеть как будут применяться стили, просто забыла удалить перед пулом.

2021-12-29 06:19 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +      margin-bottom: 40px;
Марждин удалила, согласна.

2021-12-29 06:19 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +    margin-bottom: 15px;
Марждин удалила, согласна.

2021-12-29 06:20 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +      margin-bottom: 0;
Марждин удалила, согласна.

2021-12-29 06:26 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +  align-content: flex-start;
Для align-content:  значение по умолчанию не flex-start, а - stretch. Не поправляла.

2021-12-29 09:40 UTC, Persatyi requested changes

2021-12-29 09:40 UTC, Persatyi commented on src/sass/layout/_request.scss
> +  display: flex;
Убери display: flex; на мобилке иначе input не растянется по ширине контейнера

2021-12-29 09:40 UTC, Persatyi commented on src/sass/layout/_request.scss
> +    margin-bottom: 15px;
&__label можно дать display: block; чтобы  работали маржины и использовать nth-child или first-child last-child так как нижние маржины разные. Соответственно эти стойства только для мобилки

2021-12-29 09:40 UTC, Persatyi commented on src/sass/layout/_request.scss
> +    padding-bottom: 16px;
padding-top: 16px;
 padding-bottom: 16px; - эти падинги не нужны

2021-12-29 09:40 UTC, Persatyi commented on src/sass/layout/_request.scss
> +      padding-bottom: 19px;
padding-top: 19px;
 padding-bottom: 19px; - лишнее

2021-12-29 09:40 UTC, Persatyi commented on src/sass/layout/_request.scss
> +      padding-bottom: 17px;
padding-top: 17px;
padding-bottom: 17px; - лишнее

2021-12-29 09:40 UTC, Persatyi commented on src/sass/layout/_request.scss
> +      padding-bottom: 20px;
padding-top: 20px;
padding-bottom: 20px; - лишнее

2021-12-29 10:28 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +  display: flex;
Перенесла flex на таблетку, действительно теперь в мобилке input растягиваются на всю ширину.

2021-12-29 12:58 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +      padding-bottom: 19px;
Если убираю падинги внутри input, то он схлопывается

2021-12-29 12:58 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +      padding-bottom: 17px;
Если убираю падинги внутри input, то он схлопывается

2021-12-29 12:58 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +      padding-bottom: 20px;
Если убираю падинги внутри input, то он схлопывается

2021-12-29 12:59 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +    padding-bottom: 16px;
Если убираю падинги внутри input, то он схлопывается

2021-12-29 12:59 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +    margin-bottom: 15px;
Переделала по другому, дала марджины не label, а input и сразу сработало.

2021-12-29 14:20 UTC, Persatyi requested changes

2021-12-29 14:20 UTC, Persatyi commented on src/sass/layout/_request.scss
> +    padding-bottom: 16px;
задай высоту вместо паддингов, темболее высота везде разная, на десктопе высота не соответствует высоте кнопки

2021-12-29 14:20 UTC, Persatyi commented on src/sass/base/_common.scss
> -  letter-spacing: 0.05em;
почему letter-spacing: 0.05em; убран?

2021-12-29 14:22 UTC, Persatyi commented on src/sass/layout/_request.scss
> +    margin-bottom: 15px;
не нада пробивать родителя, маржины даем соседям

2021-12-29 14:24 UTC, OlenaPatlata commented on src/sass/base/_common.scss
> -  letter-spacing: 0.05em;
Получается, что он стоит только на некоторых элементах, в основном на заголовках, ты его добавишь в title.

2021-12-29 14:50 UTC, OlenaPatlata commented on src/sass/base/_common.scss
> -  letter-spacing: 0.05em;
Падинги у input убрала и задала высоту как ты посоветовал, вышло отлично.

2021-12-29 14:52 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +    padding-bottom: 16px;
Убрала падинги, дала высоту

2021-12-29 14:52 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +      padding-bottom: 19px;
Убрала падинги, дала высоту

2021-12-29 14:52 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +      padding-bottom: 17px;
Убрала падинги, дала высоту

2021-12-29 14:52 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +      padding-bottom: 20px;
Убрала падинги, дала высоту

2021-12-29 16:25 UTC, Persatyi requested changes

2021-12-29 16:25 UTC, Persatyi commented on src/sass/layout/_request.scss
> +  &__input-first {
Это костыль, маржин задаем соседям

2021-12-29 16:25 UTC, Persatyi commented on src/sass/layout/_request.scss
> +      margin-bottom: 10px;
Это тоже костыль, задай для label через nth-child (порядковый номер)

2021-12-29 16:53 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +      margin-bottom: 10px;
Исправила, геометрия теперь задана через соседей.

2021-12-29 16:53 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +  &__input-first {
Исправила, геометрия теперь задана через соседей.

2021-12-29 20:10 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +      margin-bottom: 10px;
Убрала костыли, поставила геометрию через соседей

2021-12-29 20:10 UTC, OlenaPatlata commented on src/sass/layout/_request.scss
> +  &__input-first {
Убрала костыли, поставила геометрию через соседей

2021-12-30 12:01 UTC, Persatyi approved these changes

2021-12-30 12:14 UTC, merged