Initial settings
OlenaPatlata/team pull request #12
Opened 2021-12-29 09:30 UTC by starvadym

Ребята, посмотрите последнюю версию кода после ваших замечаний

2021-12-29 10:20 UTC, OlenaPatlata requested changes

2021-12-29 10:20 UTC, OlenaPatlata commented on src/partials/hero.html
> +    <button class="btn section hero__btn" type="button">Оставить заявку</button>
Зачем добавил здесь на кнопке класс section?

2021-12-29 10:20 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +  display: block;
Заголовок по умолчанию уже блочный элемент и у него уже есть display: block.

2021-12-29 10:20 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +  margin-bottom: 20px;
Ты добавил в h1 общий класс title, в этом классе задано изначально margin-bottom: 20px;
также задано 
 font-family: 'Inter', sans-serif;
  text-transform: uppercase;
  color: var(--color-title);
  @include font(16px, 1.5, 700);
Так что все что дублирует общий класс .title убираешь из .hero__title.

2021-12-29 10:20 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +  display: block;
<р> тоже изначально блочный элемент, проинспектируй в dev tools на вкладке computed откуда приходит display: block (находишь на вкладке computed в фильтре displayи нажимаешь на стрелочку в черном кружечке  и тебя перебрасывает на того кто дал свойство block твоему элементу.

2021-12-29 10:20 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +  margin-bottom: 20px;
Элемент p находится внутри родителя div с классом .hero__wrap-container, поэтому кнопку отталкивать должен родитель (div с классом .hero__wrap-container).

2021-12-29 10:20 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +    margin: 0;
Когда переставишь марджин на родителя, обнулять не нужно будет.

2021-12-29 10:20 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +  .hero__wrap-container {
Для обертки добавить нижний марджин 20рх для размера вьюпорта от 0 и до таблетки, чтобы оттолкнуть кнопку.

2021-12-29 15:15 UTC, starvadym commented on src/partials/hero.html
> +    <button class="btn section hero__btn" type="button">Оставить заявку</button>
Ладно, убрал. Думал добавить свойства margin-left & margin-right auto.

2021-12-29 15:15 UTC, starvadym commented on src/sass/layout/_hero.scss
> +  display: block;
Да, ты права. Убрал, уже на автомате пишу всегда.

2021-12-29 15:16 UTC, starvadym commented on src/sass/layout/_hero.scss
> +  margin-bottom: 20px;
Да, убрал все кроме letter-spacing.

2021-12-29 15:16 UTC, starvadym commented on src/sass/layout/_hero.scss
> +  display: block;
Все верно. Убрал тоже.

2021-12-29 15:17 UTC, starvadym commented on src/sass/layout/_hero.scss
> +  margin-bottom: 20px;
Да, задал отступ через родителя.

2021-12-29 15:17 UTC, starvadym commented on src/sass/layout/_hero.scss
> +    margin: 0;
Все исправлено.

2021-12-29 15:18 UTC, starvadym commented on src/sass/layout/_hero.scss
> +  .hero__wrap-container {
Да, свойство для контейнера уже добавлено. Спасибо за замечания.

2021-12-29 15:18 UTC, starvadym commented
Ребята исправил код, согласно вашим замечаниям.

2021-12-29 15:24 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +  margin-bottom: 20px;
Решили с Алексеем, что он даст letter-spacing сразу на класс .title и по секциям не нужно теперь ставить letter-spacing 0,05em, а я убрала letter-spacing 0,05em с body и не нужно его теперь по секциям обнулять.

2021-12-29 15:41 UTC, OlenaPatlata requested changes

2021-12-29 15:41 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +    letter-spacing: 0em;
Обнулять не нужно я убрала с body letter-spacing/

2021-12-29 15:41 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +@include mq(mobile-only) {
Лучше добавить вместо миксина медиаправило, тогда нижний и боковые марджины будут действовать не только на мобилке, а начиная с 0 и до таблетки.
.btn { 
    @media screen and (max-width: 767px) {
    margin-top: 30px;
    margin-left: auto;
    margin-right: auto;
  }
}

2021-12-29 15:41 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +    letter-spacing: 0.05em;
На классе .title Алексей поставит общий letter-spacing: 0.05em.

2021-12-29 15:41 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +    @include font(22px, null, null);
Эти шрифты стоят на классе .title.
.title {
  font-family: 'Inter', sans-serif;
  text-transform: uppercase;
  color: var(--color-title);
  @include font(16px, 1.5, 700);

  @include mq(mobile-only) {
    margin-bottom: 20px;
    text-align: center;
  }

  @include mq(tablet) {
    @include font(22px, null, null);
    display: flex;
    align-items: center;
  }

  @include mq(desktop) {
    @include font(30px, null, null);
  }

  @include mq(hd) {
    @include font(40px, null, null);
  }

2021-12-29 15:41 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +    letter-spacing: 0.05em;
Убираем

2021-12-29 15:41 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +    @include font(40px, 1.5, 700);
Убираем

2021-12-29 15:41 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +@include mq(mobile-only) {
Лучше добавить вместо миксина медиаправило, тогда нижний марджин будет действовать не только на мобилке, а начиная с 0 и до таблетки.
.hero__wrap-container {
@media screen and (max-width: 767px) {
margin-bottom: 20px;
}
}

2021-12-29 21:07 UTC, starvadym commented on src/sass/layout/_hero.scss
> +  margin-bottom: 20px;
Ок. Все убрал.

2021-12-29 21:07 UTC, starvadym commented on src/sass/layout/_hero.scss
> +    letter-spacing: 0em;
Ok

2021-12-29 21:10 UTC, starvadym commented on src/sass/layout/_hero.scss
> +@include mq(mobile-only) {
На макете в мобильном формате кнопка сверху имеет отступ 20 пикселей а снизу 30. В общем исправил.

2021-12-29 21:10 UTC, starvadym commented on src/sass/layout/_hero.scss
> +    letter-spacing: 0.05em;
ОК

2021-12-29 21:11 UTC, starvadym commented on src/sass/layout/_hero.scss
> +    @include font(22px, null, null);
Понял. Все убрал.

2021-12-29 21:11 UTC, starvadym commented on src/sass/layout/_hero.scss
> +    letter-spacing: 0.05em;
ОК

2021-12-29 21:11 UTC, starvadym commented on src/sass/layout/_hero.scss
> +    @include font(40px, 1.5, 700);
ОК

2021-12-29 21:12 UTC, starvadym commented on src/sass/layout/_hero.scss
> +@include mq(mobile-only) {
ОК

2021-12-29 21:12 UTC, starvadym commented
Ребята, исправил.

2022-01-02 15:15 UTC, OlenaPatlata requested changes
Определись какие фото используешь для слайдера, ты подключил два комплекта в папке images и в папке img-hero. Один комплект нужно удалить.

2022-01-02 15:15 UTC, OlenaPatlata commented on src/index.html
> +    <include src="./partials/hero.html"></include>
Зачем второй раз подключил hero после примера? Нужно удалить строку 27.

2022-01-02 15:15 UTC, OlenaPatlata commented on src/sass/_hero.scss
> +.hero {
УДАЛИТЬ  полностью файл _hero.scss подключенный в папке sass.

2022-01-02 15:15 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +    padding-bottom: 80px;
Удалить в этой секции нетнажнего падинга начиная с таблетки.

2022-01-02 15:15 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +    padding-bottom: 70px;
Поставить padding-bottom: 0p; начиная с таблетки секция hero вплотную слайдером прилегает к следующей секции.

2022-01-02 15:15 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +    margin: 0;
Обнуляющий марджин не нужен, так как для общего класса .title нижний марджин задан только до таблетки.

2022-01-02 15:15 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +    text-align: left;
Не нужно задавать text-align: left, сохраняется свойство заданное ещё на таблетке.

2022-01-02 15:15 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +    text-align: left;
Не нужно задавать text-align: left, сохраняется свойство заданное ещё на таблетке.

2022-01-02 15:15 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +    text-align: left;
Не нужно задавать text-align: left, сохраняется свойство заданное ещё на таблетке.

2022-01-02 15:15 UTC, OlenaPatlata commented on src/sass/layout/_hero.scss
> +    text-align: left;
Не нужно задавать text-align: left, сохраняется свойство заданное ещё на таблетке.

2022-01-02 15:57 UTC, starvadym commented on src/index.html
> +    <include src="./partials/hero.html"></include>
ДА, удалил.

2022-01-02 15:57 UTC, starvadym commented on src/sass/_hero.scss
> +.hero {
Да, удалил

2022-01-02 16:09 UTC, starvadym commented on src/sass/layout/_hero.scss
> +    text-align: left;
Убрал.

2022-01-02 16:09 UTC, starvadym commented on src/sass/layout/_hero.scss
> +    text-align: left;
Убрал.

2022-01-02 16:09 UTC, starvadym commented on src/sass/layout/_hero.scss
> +    text-align: left;
Убрал.

2022-01-02 16:09 UTC, starvadym commented on src/sass/layout/_hero.scss
> +    text-align: left;
Убрал.

2022-01-02 16:09 UTC, starvadym commented on src/sass/layout/_hero.scss
> +    margin: 0;
Убрал.

2022-01-02 16:09 UTC, starvadym commented on src/sass/layout/_hero.scss
> +    padding-bottom: 70px;
Убрал.

2022-01-02 16:09 UTC, starvadym commented on src/sass/layout/_hero.scss
> +    padding-bottom: 80px;
Удалил

2022-01-03 10:15 UTC, OlenaPatlata approved these changes

2022-01-03 10:16 UTC, merged