Формирует футтер
OlenaPatlata/team pull request #14
Opened 2021-12-30 21:31 UTC by OlenaPatlata

Проблема с фоном на логотипах, пока не решила

2022-01-01 15:25 UTC, Persatyi requested changes

2022-01-01 15:25 UTC, Persatyi commented on src/partials/footer.html
> +      <picture>
Лого должен быть в формате svg или png так как на макете под ним видно серый цвет (прозрачные участки). Проще спрайт засунуть.

2022-01-02 14:25 UTC, OlenaPatlata commented on src/partials/footer.html
> +      <picture>
Переделала на png (в спрайт не засовывала так как не выкачиваются svg).

2022-01-02 15:06 UTC, Persatyi approved these changes

2022-01-02 15:16 UTC, merged