Feature/about us
OlenaPatlata/team pull request #16
Opened 2021-12-31 04:31 UTC by vatakusi

2 секции: "О нас" и "Контакты"

2022-01-01 15:26 UTC, Persatyi commented
Круто сделано

2022-01-02 12:02 UTC, OlenaPatlata requested changes

2022-01-02 12:02 UTC, OlenaPatlata commented on src/index.html
> +    <include src="./partials/contacts.html"></include>
Секцию contacts нужно подключить после секции request, как указано на макете.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/partials/about-us.html
> +      <h2 class="aboutus__title">о нас</h2>
Добавить для h2 общий класс  title, в котором прописаны общие стили для заголовков.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +    &-pitch {
Заменить стили для класса .aboutus__items-pitch (так как в карточках разный отступ от текста до низа карточки, что зависит от того одна строчка текста или две)
Убрать: padding-bottom: 39px;- когда две строчки текста его выпирает из карточки.
Добавить:
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: center;
    align-content: center;
    height: 100%;

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +    &-three {
Для класса .aboutus__title-three убрать из стилей:
    max-width: 250px; 
    margin: auto;
В карточках в mobile разный отступ от этого текста до низа карточки, что зависит от того одна строчка текста или две, ниже также указано про необходимость внесения изменений в стили для класса .aboutus__items-pitch.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +    width: 290px;
Убрать в стилях    для класса .aboutus__items ширину 290рх, ширину не ограничиваем. Ширину  вычисляем используя калькулятор  начиная с таблетки width: calc(100% / 2 - 30px); начиная с десктопа     width: calc(100% / 3 - 30px). То есть убрать все ширины в пикселях, от 0 и в мобилке ширина 100%, дальше только через calc.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +      display: block;
В общих стилях _reset.scss уже задано для всех svg свойство display: block,поэтому здесь нужно убрать display: block.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/partials/about-us.html
> +            <use href="images/sprite.svg#support-1" width="50" height="50"></use>
Убрать высоту и ширину, они заданы в стилях.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/partials/about-us.html
> +            <use href="images/sprite.svg#manufacturing-1" width="50" height="50"></use>
Убрать высоту и ширину, они заданы в стилях.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +  &__title {
С 23 по 55 строку убрать все стили, они полностью дублируют стили прописанные для класса title (то что в общих стилях title  задано mardgin-top 20 рх только для мобилки я вижу, Алексей это исправит - нужно от 0 и до 767 рх).

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +    margin-bottom: 20px;
Убрать марджин, толкать вниз должен родитель div с классом .aboutus__title-wrap, который оборачивает h2 и p.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +    &-wrap {
Добавить сразу марджин нижний 20 рх, чтобы оттолкнуть первую карточку.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +      @include mq(tablet) {
Изменить нижний марджин на 50рх согласно макета.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +      &:nth-child(-n + 3) {
Лучше дать родителю ul отрицательный марджин, а  детям li положительные марджины, тогда не нужно использовать разные вариации nth-child(-n + 3). Особенность с отрицательными марджинами только в таблетке, там верх и низ по 20, а лево-право по 30рх, значит родителю ul
    margin-bottom: -10px;
    margin-top: -10px;
    margin-left: -15px;
    margin-right: -15px;
А детям li
    margin-bottom: 10px;
    margin-top: 10px;
    margin-right: 15px;
    margin-left: 15px;
Начиная с десктопа у родителя     margin: -15px; у детей     margin: 15px;

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +      margin: auto;
margin: auto; убрать, центрировать флексом

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +      margin-bottom: 15px;
margin-bottom: 15px; по макету только до таблетки, добавить условия что в таблетке уже 30рх.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +      @include mq(tablet) {
Добавить обязательно к флексу:
    justify-content: center;
    width: 100%;

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +      padding-bottom: 39px;
Убрать

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_contacts.scss
> +    padding-top: 90px;
Добавить padding-bottom: 90px;

2022-01-02 12:02 UTC, OlenaPatlata commented on src/partials/contacts.html
> +  <div class="contacts container">
Из-за того что у секции и контейнера задан одинаковый класс contacts произошло дублирование стилей секции на контейнер и сверху теперь два паддинга по 90рх и у секции и у контейнера (чтобы меньше править кода убрать вообще класс contacts у секции, а добавить общий класс section).

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_contacts.scss
> +      margin-bottom: 10px;
Добавить условие в 79 строке, что margin-bottom: 10px кроме последнего li

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_contacts.scss
> +    display: block;
Добавить margin-bottom: 15px; чтобы оттолкнуть карту.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_contacts.scss
> +      margin-bottom: 60px;
Исправить в таблетке на margin-bottom: 50px согласно макету, с десктопа уже дать 60рх, для hd - 70рх.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_contacts.scss
> +      width: 100%;
Добавить margin-bottom: 60px; а для hd уже margin-bottom:70рх.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/partials/contacts.html
> +      <div class="rekviz__title-wrap">
Зачем добавляли div с классом .rekviz__title-wrap, если потом он в стилях вообще не участвует? 
Можно использовать этот div как родитель с позицией relative для иконки (кружок и стрелка вверх) с позицией абсолют.

2022-01-02 12:02 UTC, OlenaPatlata commented on src/sass/layouts/_contacts.scss
> +  &__title {
Аналогично как и для секции "О нас" убрать общие стили с класса .contacts__title, они повторяют класс .title. Дать классу .contacts__title только стили внешней геометрии.

2022-01-02 14:37 UTC, vatakusi commented on src/sass/layouts/_about-us.scss
> +    &-pitch {
точно, выпирает, но достаточно убрать только padding-bottom: 39px и выпадение снизу уходит; остальное (флекс и ниже для добавления) "ломает" внутри items структуру.

2022-01-02 16:04 UTC, vatakusi commented on src/sass/layouts/_about-us.scss
> +    &-three {
max-width: 250px; необходим для правильного переноса текста, иначе лишние слова остаются в строке вместо переноса как на макете.

2022-01-02 16:14 UTC, vatakusi commented on src/sass/layouts/_about-us.scss
> +    width: 290px;
ок, поменял, но не совсем понял приоритет такого подхода, поскольку calc() сам по себе нагружает, хоть и незначительно, вычислительные ресурсы. В данной правке мы приходим к той-же ширине что задана, только путем допвычисления.

2022-01-02 16:21 UTC, vatakusi commented on src/sass/layouts/_contacts.scss
> +    display: block;
в мобильной версии этот зазор задан в селекторе всего списка адресов - contacts__list

2022-01-02 16:22 UTC, vatakusi commented on src/sass/layouts/_contacts.scss
> +      margin-bottom: 60px;
+

2022-01-02 16:47 UTC, vatakusi commented on src/partials/contacts.html
> +      <div class="rekviz__title-wrap">
иначе borfer расползается в  мобильное версии - по горизонтали, в остальных по вертикали. А так wrap задает ему форму независимо от экрана и влияния display: block; 
Добавил position: relative для иконки-свайпера

2022-01-02 16:52 UTC, vatakusi commented on src/sass/layouts/_contacts.scss
> +  &__title {
ок, только почему то общий title не срабатывает

2022-01-02 17:31 UTC, vatakusi commented on src/sass/layouts/_about-us.scss
> +  &__title {
закомментил

2022-01-02 17:41 UTC, vatakusi commented on src/sass/layouts/_about-us.scss
> +      &:nth-child(-n + 3) {
отрицательные марджины хороши на скорую руку. Текущий подход мне кажется более точечным, оставлю его с Вашего разрешения ))

2022-01-02 18:19 UTC, vatakusi commented on src/sass/layouts/_about-us.scss
> +      margin: auto;
в этой версии к классу флекс не примениться. Только через родителя aboutus__items-pitch {align-items: center;} который в мобильной версии блочный и чтобы перенести туда выравнивание нужно дополнительно задать ему флекс. Одна строка выглядит логичнее, поскольку дисплей: блок; по умолчанию

2022-01-02 18:23 UTC, vatakusi commented on src/sass/layouts/_about-us.scss
> +      @include mq(tablet) {
добавил, но чудесно работает без него

2022-01-03 08:05 UTC, vatakusi commented on src/partials/contacts.html
> +  <div class="contacts container">
переназвал класс: "contacts-" и добавил общий класс "section"

2022-01-03 09:17 UTC, OlenaPatlata requested changes
Нужно чтобы Вы удалили лишние спрайты, так в html у Вас подключены иконки из sprite.svg, но также Вы добавили еще два спрайта symbol-defs.svg (один в папке images, другой в папке about-us-icon. Если в этих спрайтах есть иконки, которые будете использовать, то скопируйте и перенесите их в sprite.svg.

2022-01-03 09:17 UTC, OlenaPatlata commented on src/partials/about-us.html
> +            <use href="images/sprite.svg#manufacturing-1" width="50" height="50"></use>
Нужно убрать высоту и ширину для иконки иначе она не будет менять размеры на таблетке и не станет 60/60

2022-01-03 09:17 UTC, OlenaPatlata commented on src/partials/about-us.html
> +            <use href="images/sprite.svg#support-1" width="50" height="50"></use>
Нужно убрать высоту и ширину для иконки иначе она не будет менять размеры на таблетке и не станет 60/60

2022-01-03 09:17 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +      width: calc(100% / 2 - 30px);
Нужно исправить, если не используем отрицательные марджины, тогда  убираете calc и ставите width: 324px.

2022-01-03 09:17 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +  &__title {
Стили для title написаны, но пока не подключены в main.scss, поэтому не применяются. Алексей закончит свою ветку и тогда подключит их в main.scss.

2022-01-03 09:17 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +      }
Для hd размер шрифта уже 20рх, нужно добавить ещё одно правило.

2022-01-03 09:17 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +    margin-bottom: 20px;
Почему не убрали margin-bottom: 20px;? Этот марджин пробивает родителя на мобильной версии, а на остальных версиях добавляется к марджину родителя, что увеличивает отступ на лишние 20рх.

2022-01-03 09:17 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +      width: calc(100% / 3 - 30px);
Без отрицательных марджинов смысла в использовании calc  нет, так что возвращайте width: 290px; и убирайте  width: calc(100% / 3 - 30px);.

2022-01-03 09:17 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +      display: block;
?

2022-01-03 09:17 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +    width: 290px;
Calc отлично работает вместе с отрицательными марджинами, если не используете отрицательные марджины, то и calc не нужен.

2022-01-03 09:17 UTC, OlenaPatlata commented on src/partials/contacts.html
> +  <div class="contacts container">
Нельзя назвать класс .contacts-, пусть будет .contacts-section и общий класс .section

2022-01-03 09:17 UTC, OlenaPatlata commented on src/sass/layouts/_contacts.scss
> +    display: block;
Задав классу .contacts__list margin-bottom: 15px вы пробили двух родителей address class="contacts__adress" и div class="contacts__text-wrap". 
Отталкиваться должны соседние элементы, значит div class="contacts__text-wrap" должен оттолкнуть нижним марджином div class="contacts__map".

2022-01-03 09:17 UTC, OlenaPatlata commented on src/sass/layouts/_contacts.scss
> +    padding-top: 90px;
Не добавили padding-bottom: 90px для класса .contacts и на таблетке нижний паддинг остался с мобилки 40рх,чтоне соответствует макету, нужно 90рх.

2022-01-03 09:17 UTC, OlenaPatlata commented on src/sass/layouts/_contacts.scss
> +  &__title {
Стили для title написаны, но пока не подключены в main.scss, поэтому не применяются. Алексей закончит свою ветку и тогда подключит их в main.scss.

2022-01-03 09:17 UTC, OlenaPatlata commented on src/sass/layouts/_contacts.scss
> +      width: 100%;
Забыли добавить margin-bottom: 60px; а для hd уже margin-bottom:70рх.

2022-01-03 14:43 UTC, vatakusi commented on src/sass/layouts/_about-us.scss
> +      display: block;
я его не вижу у себя в vccode. Я его не задавал.
display: block по умолчанию идет если не указано иное.

2022-01-03 16:11 UTC, vatakusi commented on src/sass/layouts/_about-us.scss
> +    width: 290px;
ок, чтобы не бегать туда-сюда два раза, оставляю "калк"

2022-01-03 16:12 UTC, vatakusi commented on src/partials/about-us.html
> +            <use href="images/sprite.svg#support-1" width="50" height="50"></use>
убрал, сейчас еще раз "запулю"

2022-01-03 16:14 UTC, vatakusi commented on src/sass/layouts/_about-us.scss
> +    margin-bottom: 20px;
убрал, видимо старая версия. Сейчас "запулю" новую.

2022-01-03 16:16 UTC, vatakusi commented on src/sass/layouts/_contacts.scss
> +    padding-top: 90px;
видимо все таки старая версия

2022-01-03 16:17 UTC, vatakusi commented on src/sass/layouts/_contacts.scss
> +    padding-top: 90px;
добавил

2022-01-03 16:18 UTC, vatakusi commented on src/partials/contacts.html
> +  <div class="contacts container">
длинные классы сбивают меня с толку, ну ок, переназвал ))

2022-01-03 16:22 UTC, vatakusi commented on src/sass/layouts/_contacts.scss
> +    display: block;
ок, исправил

2022-01-03 16:25 UTC, vatakusi commented on src/sass/layouts/_contacts.scss
> +      width: 100%;
поправил

2022-01-03 19:00 UTC, vatakusi commented on src/sass/layouts/_about-us.scss
> +      }
поправил, у меня макете правда - 22px;

2022-01-04 17:02 UTC, OlenaPatlata requested changes
Пару правок и будет готово.

2022-01-04 17:02 UTC, OlenaPatlata commented on src/partials/contacts.html
> +  <div class="contacts container">
Это Вы еще не видели как названы классы у Вадима и Алексея на слайдерах.

2022-01-04 17:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +    width: 290px;
Повторяю, эта формула работает только в комплексе с отрицательными марджинами у родителя, поэтому убираем calc, возвращаем width.

2022-01-04 17:02 UTC, OlenaPatlata commented on src/sass/layouts/_about-us.scss
> +      width: calc(100% / 3 - 30px);
Повторяю: возвращайте width: 290px; и убирайте width: calc(100% / 3 - 30px), без отрицательных марджинов эта формула работает не правильно и тогда ширина карточек меньше чем на макете.

2022-01-04 17:29 UTC, vatakusi commented on src/partials/contacts.html
> +  <div class="contacts container">
вернул старое название поскольку фон получается уже не "резиновый" и переопределять по БЭМу не понятно зачем. Конейнер имеет глобальную настройку с цветом фона для всех форматов

2022-01-04 18:12 UTC, OlenaPatlata approved these changes

2022-01-04 18:30 UTC, merged