Feature/hero with slider
OlenaPatlata/team pull request #17
Opened 2022-01-03 11:21 UTC by starvadym

Ребята, посмотрите на эту сборку со слайдером.

2022-01-04 19:27 UTC, Persatyi requested changes

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    height: 12px;
По макету стрелка идет 12х12

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    background-size: cover;
background-size: cover; - напишы contain и иконка 12х12 не будет вылазить

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    height: 12px;
так же 12х12

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    background-size: cover;
вмето cover - contain

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    height: 14px;
должно быть 16х16

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    background-size: cover;
background-size: cover; поменять на contain

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    height: 14px;
16x16

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    background-size: cover;
background-size: cover; - поменять на contain

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    height: 16px;
width: 14px;
    height: 16px; - поменять на 16х16

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    background-size: cover;
background-size: cover; - поменять на contain

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    height: 16px;
width: 14px;
height: 16px; - поменять на 16х16

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    background-size: cover;
background-size: cover; - поменять на contain

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    height: 12px;
поменять везде где не соответствует макету

2022-01-04 19:27 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    background-size: cover;
background-size: cover; на contain

2022-01-04 19:29 UTC, Persatyi commented
Слишком много повторяющегося кода,

2022-01-04 20:50 UTC, Persatyi requested changes

2022-01-04 20:50 UTC, Persatyi commented on src/sass/components/_hero-slider.scss
> +    background-image: url("data:image/svg+xml;charset=UTF-8,%3csvg width='14' height='16' viewBox='0 0 14 16' fill='none' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M-4.23664e-07 8L13.5 0.205772
сного дублей одной картинки

2022-01-06 20:04 UTC, starvadym commented on src/sass/components/_hero-slider.scss
> +    height: 12px;
Все исправил

2022-01-06 20:04 UTC, starvadym commented on src/sass/components/_hero-slider.scss
> +    background-size: cover;
Исправлено.

2022-01-06 20:04 UTC, starvadym commented on src/sass/components/_hero-slider.scss
> +    height: 12px;
Ок, исправлено

2022-01-06 20:05 UTC, starvadym commented on src/sass/components/_hero-slider.scss
> +    background-size: cover;
Да добавил contain свойство.

2022-01-06 20:05 UTC, starvadym commented on src/sass/components/_hero-slider.scss
> +    height: 14px;
Ок, исправлено.

2022-01-06 20:05 UTC, starvadym commented on src/sass/components/_hero-slider.scss
> +    background-size: cover;
Все исправлено.

2022-01-06 20:06 UTC, starvadym commented on src/sass/components/_hero-slider.scss
> +    height: 16px;
Да, исправил.

2022-01-06 20:06 UTC, starvadym commented on src/sass/components/_hero-slider.scss
> +    background-size: cover;
Да, исправил.

2022-01-06 20:06 UTC, starvadym commented on src/sass/components/_hero-slider.scss
> +    height: 12px;
Ок. Исправлено.

2022-01-06 20:06 UTC, starvadym commented on src/sass/components/_hero-slider.scss
> +    background-size: cover;
Ок. Исправлено.

2022-01-06 20:08 UTC, starvadym commented on src/sass/components/_hero-slider.scss
> +    background-image: url("data:image/svg+xml;charset=UTF-8,%3csvg width='14' height='16' viewBox='0 0 14 16' fill='none' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M-4.23664e-07 8L13.5 0.205772
Да. Оставил всего 4 картинки - стрелки лево право обычные и стрелки лево право в отключенном состоянии.

2022-01-08 10:36 UTC, Persatyi approved these changes

2022-01-08 12:07 UTC, merged